/* ════════════════════════════════════════════════════════════════
   GAME DATA — BreakingLab  (GENERADO por tools/generate_data.py)
   No editar a mano: ejecuta el generador para regenerar.
   43 elementos de batalla + 7 hechizos = 50 cartas.
   290 moléculas/elementos nativos reales.
   ids de cada molécula = orden de lectura de la fórmula.
   ATK/DEF de molécula = suma de los stats de sus elementos.
════════════════════════════════════════════════════════════════ */

const RADIOACTIVE = ["U", "Ra", "Po"];

/* ── Elementos de batalla ── */
const ELEMENTS = [
  {id:"H", sym:"H", name:"Hidrógeno", num:1, atk:1, def:2, type:'nonmetal', img:'img/H.png',
   eff:"⚔️🛡 Ataque/Defensa: combínala en el orden de la fórmula para formar una molécula y batirte.", info:"El elemento más abundante del universo.",
   hist:"Cavendish lo aisló en 1766; Lavoisier lo llamó «creador de agua». Es el combustible de las estrellas."},
  {id:"Li", sym:"Li", name:"Litio", num:3, atk:2, def:3, type:'nonmetal', img:'img/Li.png',
   eff:"⚔️🛡 Ataque/Defensa: combínala en el orden de la fórmula para formar una molécula y batirte.", info:"El metal más ligero que existe.",
   hist:"Arfwedson lo halló en 1817 en una mina sueca. Hoy mueve el mundo dentro de las baterías."},
  {id:"Be", sym:"Be", name:"Berilio", num:4, atk:3, def:6, type:'nonmetal', img:'img/Be.png',
   eff:"⚔️🛡 Ataque/Defensa: combínala en el orden de la fórmula para formar una molécula y batirte.", info:"Ligero y rígido: aeroespacial.",
   hist:"Vauquelin lo descubrió en 1798 analizando esmeraldas: el berilo le dio nombre."},
  {id:"B", sym:"B", name:"Boro", num:5, atk:3, def:2, type:'nonmetal', img:'img/B.png',
   eff:"⚔️🛡 Ataque/Defensa: combínala en el orden de la fórmula para formar una molécula y batirte.", info:"Esencial en vidrios resistentes.",
   hist:"Gay-Lussac y Davy lo aislaron casi a la vez en 1808. Endurece el vidrio borosilicatado de tu laboratorio."},
  {id:"C", sym:"C", name:"Carbono", num:6, atk:2, def:2, type:'nonmetal', img:'img/C.png',
   eff:"⚔️🛡 Ataque/Defensa: combínala en el orden de la fórmula para formar una molécula y batirte.", info:"El elemento de la vida.",
   hist:"Conocido desde la prehistoria como carbón y hollín. Según ordene sus átomos es lápiz… o diamante."},
  {id:"N", sym:"N", name:"Nitrógeno", num:7, atk:2, def:2, type:'nonmetal', img:'img/N.png',
   eff:"⚔️🛡 Ataque/Defensa: combínala en el orden de la fórmula para formar una molécula y batirte.", info:"Compone el 78% del aire.",
   hist:"Rutherford lo aisló en 1772. Su nombre francés, azote, significa «sin vida»; hoy fertiliza al mundo."},
  {id:"O", sym:"O", name:"Oxígeno", num:8, atk:2, def:1, type:'nonmetal', img:'img/O.png',
   eff:"⚔️🛡 Ataque/Defensa: combínala en el orden de la fórmula para formar una molécula y batirte.", info:"21% de la atmósfera.",
   hist:"Scheele y Priestley lo aislaron (1771-74); Lavoisier lo entendió y fundó la química moderna."},
  {id:"F", sym:"F", name:"Flúor", num:9, atk:2, def:1, type:'nonmetal', img:'img/F.png',
   eff:"⚔️🛡 Ataque/Defensa: combínala en el orden de la fórmula para formar una molécula y batirte.", info:"El elemento más reactivo.",
   hist:"Moissan lo domó en 1886 tras décadas de intentos que costaron salud (y vidas) a varios químicos."},
  {id:"Na", sym:"Na", name:"Sodio", num:11, atk:2, def:2, type:'nonmetal', img:'img/Na.png',
   eff:"⚔️🛡 Ataque/Defensa: combínala en el orden de la fórmula para formar una molécula y batirte.", info:"Explota en contacto con agua.",
   hist:"Davy lo aisló en 1807 por electrólisis. La mitad de la sal de tu cocina."},
  {id:"Mg", sym:"Mg", name:"Magnesio", num:12, atk:2, def:3, type:'nonmetal', img:'img/Mg.png',
   eff:"⚔️🛡 Ataque/Defensa: combínala en el orden de la fórmula para formar una molécula y batirte.", info:"Arde con luz blanca cegadora.",
   hist:"Davy lo aisló en 1808. Iluminó los primeros flashes de fotografía."},
  {id:"Al", sym:"Al", name:"Aluminio", num:13, atk:3, def:3, type:'nonmetal', img:'img/Al.png',
   eff:"⚔️🛡 Ataque/Defensa: combínala en el orden de la fórmula para formar una molécula y batirte.", info:"El metal más abundante de la corteza.",
   hist:"Wöhler lo obtuvo puro en 1827; fue más caro que el oro hasta dominarse su electrólisis."},
  {id:"Si", sym:"Si", name:"Silicio", num:14, atk:3, def:3, type:'nonmetal', img:'img/Si.png',
   eff:"⚔️🛡 Ataque/Defensa: combínala en el orden de la fórmula para formar una molécula y batirte.", info:"La base de toda la electrónica.",
   hist:"Berzelius lo aisló en 1824. De la arena de playa a los chips de tu móvil."},
  {id:"P", sym:"P", name:"Fósforo", num:15, atk:3, def:3, type:'nonmetal', img:'img/P.png',
   eff:"⚔️🛡 Ataque/Defensa: combínala en el orden de la fórmula para formar una molécula y batirte.", info:"Guarda la energía del ADN.",
   hist:"Brand lo descubrió en 1669 destilando orina en busca de la piedra filosofal: brillaba en la oscuridad."},
  {id:"S", sym:"S", name:"Azufre", num:16, atk:3, def:1, type:'nonmetal', img:'img/S.png',
   eff:"⚔️🛡 Ataque/Defensa: combínala en el orden de la fórmula para formar una molécula y batirte.", info:"El «fuego y azufre» bíblico.",
   hist:"Conocido desde la antigüedad; Lavoisier probó en 1777 que era un elemento. Potenció la pólvora."},
  {id:"Cl", sym:"Cl", name:"Cloro", num:17, atk:2, def:1, type:'nonmetal', img:'img/Cl.png',
   eff:"⚔️🛡 Ataque/Defensa: combínala en el orden de la fórmula para formar una molécula y batirte.", info:"Desinfecta el agua del planeta.",
   hist:"Scheele lo obtuvo en 1774. Salva millones de vidas potabilizando agua… y fue arma en 1915."},
  {id:"K", sym:"K", name:"Potasio", num:19, atk:2, def:2, type:'nonmetal', img:'img/K.png',
   eff:"⚔️🛡 Ataque/Defensa: combínala en el orden de la fórmula para formar una molécula y batirte.", info:"Imprescindible para tus neuronas.",
   hist:"Davy lo aisló en 1807: el primer metal obtenido por electrólisis. Arde en violeta."},
  {id:"Ca", sym:"Ca", name:"Calcio", num:20, atk:2, def:3, type:'nonmetal', img:'img/Ca.png',
   eff:"⚔️🛡 Ataque/Defensa: combínala en el orden de la fórmula para formar una molécula y batirte.", info:"Construye huesos y montañas.",
   hist:"Davy lo aisló en 1808. La cal con la que Roma levantó su imperio era su óxido."},
  {id:"Ti", sym:"Ti", name:"Titanio", num:22, atk:3, def:4, type:'nonmetal', img:'img/Ti.png',
   eff:"⚔️🛡 Ataque/Defensa: combínala en el orden de la fórmula para formar una molécula y batirte.", info:"Tan fuerte como ligero.",
   hist:"Gregor lo halló en 1791. De las prótesis de cadera a los motores de los cohetes."},
  {id:"V", sym:"V", name:"Vanadio", num:23, atk:3, def:4, type:'nonmetal', img:'img/V.png',
   eff:"⚔️🛡 Ataque/Defensa: combínala en el orden de la fórmula para formar una molécula y batirte.", info:"Endurece los aceros.",
   hist:"Del Río lo descubrió en México en 1801, pero no le creyeron; Sefström lo redescubrió en 1830."},
  {id:"Cr", sym:"Cr", name:"Cromo", num:24, atk:3, def:5, type:'nonmetal', img:'img/Cr.png',
   eff:"⚔️🛡 Ataque/Defensa: combínala en el orden de la fórmula para formar una molécula y batirte.", info:"El brillo de los cromados.",
   hist:"Vauquelin lo aisló en 1797. Da su rojo al rubí y su verde a la esmeralda."},
  {id:"Mn", sym:"Mn", name:"Manganeso", num:25, atk:2, def:4, type:'nonmetal', img:'img/Mn.png',
   eff:"⚔️🛡 Ataque/Defensa: combínala en el orden de la fórmula para formar una molécula y batirte.", info:"Imprescindible en el acero.",
   hist:"Gahn lo aisló en 1774. Los pigmentos de las cuevas de Altamira ya lo contenían."},
  {id:"Fe", sym:"Fe", name:"Hierro", num:26, atk:2, def:3, type:'nonmetal', img:'img/Fe.png',
   eff:"⚔️🛡 Ataque/Defensa: combínala en el orden de la fórmula para formar una molécula y batirte.", info:"El esqueleto de la civilización.",
   hist:"Forjado desde hace 5.000 años; los primeros hierros fueron meteoritos caídos del cielo."},
  {id:"Co", sym:"Co", name:"Cobalto", num:27, atk:4, def:4, type:'nonmetal', img:'img/Co.png',
   eff:"⚔️🛡 Ataque/Defensa: combínala en el orden de la fórmula para formar una molécula y batirte.", info:"Azul de los maestros vidrieros.",
   hist:"Brandt lo aisló en 1735: el primer metal descubierto desde la antigüedad. Su nombre viene de los kobold, duendes mineros."},
  {id:"Ni", sym:"Ni", name:"Níquel", num:28, atk:3, def:5, type:'nonmetal', img:'img/Ni.png',
   eff:"⚔️🛡 Ataque/Defensa: combínala en el orden de la fórmula para formar una molécula y batirte.", info:"Resiste la corrosión.",
   hist:"Cronstedt lo aisló en 1751 del «cobre del diablo» que frustraba a los mineros alemanes."},
  {id:"Cu", sym:"Cu", name:"Cobre", num:29, atk:2, def:3, type:'nonmetal', img:'img/Cu.png',
   eff:"⚔️🛡 Ataque/Defensa: combínala en el orden de la fórmula para formar una molécula y batirte.", info:"Conduce la electricidad del mundo.",
   hist:"Trabajado desde hace 10.000 años; dio nombre a una era entera de la humanidad."},
  {id:"Zn", sym:"Zn", name:"Cinc", num:30, atk:2, def:4, type:'nonmetal', img:'img/Zn.png',
   eff:"⚔️🛡 Ataque/Defensa: combínala en el orden de la fórmula para formar una molécula y batirte.", info:"Protege al acero del óxido.",
   hist:"Conocido en la India medieval; Marggraf lo describió en Europa en 1746. Galvaniza el mundo."},
  {id:"As", sym:"As", name:"Arsénico", num:33, atk:3, def:3, type:'nonmetal', img:'img/As.png',
   eff:"⚔️🛡 Ataque/Defensa: combínala en el orden de la fórmula para formar una molécula y batirte.", info:"El veneno de los Borgia.",
   hist:"Alberto Magno lo aisló hacia 1250. Durante siglos fue «el polvo de la herencia»."},
  {id:"Se", sym:"Se", name:"Selenio", num:34, atk:4, def:2, type:'nonmetal', img:'img/Se.png',
   eff:"⚔️🛡 Ataque/Defensa: combínala en el orden de la fórmula para formar una molécula y batirte.", info:"Fotosensible: ve la luz.",
   hist:"Berzelius lo descubrió en 1817 y lo nombró por Selene, la Luna. Hizo posibles las primeras fotocopias."},
  {id:"Br", sym:"Br", name:"Bromo", num:35, atk:3, def:1, type:'nonmetal', img:'img/Br.png',
   eff:"⚔️🛡 Ataque/Defensa: combínala en el orden de la fórmula para formar una molécula y batirte.", info:"Único no metal líquido.",
   hist:"Balard lo aisló en 1826 de las salinas. Su nombre significa «hedor»… con razón."},
  {id:"Sr", sym:"Sr", name:"Estroncio", num:38, atk:3, def:4, type:'nonmetal', img:'img/Sr.png',
   eff:"⚔️🛡 Ataque/Defensa: combínala en el orden de la fórmula para formar una molécula y batirte.", info:"El rojo de los fuegos artificiales.",
   hist:"Descubierto en 1790 en un mineral escocés de Strontian. Tiñe de carmesí la pirotecnia."},
  {id:"Mo", sym:"Mo", name:"Molibdeno", num:42, atk:4, def:5, type:'nonmetal', img:'img/Mo.png',
   eff:"⚔️🛡 Ataque/Defensa: combínala en el orden de la fórmula para formar una molécula y batirte.", info:"Acero de blindajes y motores.",
   hist:"Scheele lo distinguió del plomo en 1778; Hjelm lo aisló en 1781."},
  {id:"Ag", sym:"Ag", name:"Plata", num:47, atk:2, def:3, type:'nonmetal', img:'img/Ag.png',
   eff:"⚔️🛡 Ataque/Defensa: combínala en el orden de la fórmula para formar una molécula y batirte.", info:"El metal que mejor conduce.",
   hist:"Trabajada desde hace 5.000 años; mató más bacterias que muchos antibióticos."},
  {id:"Cd", sym:"Cd", name:"Cadmio", num:48, atk:3, def:5, type:'nonmetal', img:'img/Cd.png',
   eff:"⚔️🛡 Ataque/Defensa: combínala en el orden de la fórmula para formar una molécula y batirte.", info:"Tóxico y fotovoltaico.",
   hist:"Stromeyer lo halló en 1817 como impureza amarilla en minerales de cinc."},
  {id:"Sn", sym:"Sn", name:"Estaño", num:50, atk:3, def:4, type:'nonmetal', img:'img/Sn.png',
   eff:"⚔️🛡 Ataque/Defensa: combínala en el orden de la fórmula para formar una molécula y batirte.", info:"Unió el bronce y la lata.",
   hist:"Con él nació la Edad del Bronce hace 5.000 años. Napoleón perdió botones (y soldados) por su «peste» en el frío ruso."},
  {id:"Sb", sym:"Sb", name:"Antimonio", num:51, atk:3, def:4, type:'nonmetal', img:'img/Sb.png',
   eff:"⚔️🛡 Ataque/Defensa: combínala en el orden de la fórmula para formar una molécula y batirte.", info:"Cosmética y balas antiguas.",
   hist:"Usado como kohl en el antiguo Egipto; descrito por alquimistas medievales."},
  {id:"I", sym:"I", name:"Yodo", num:53, atk:3, def:1, type:'nonmetal', img:'img/I.png',
   eff:"⚔️🛡 Ataque/Defensa: combínala en el orden de la fórmula para formar una molécula y batirte.", info:"Tu tiroides lo necesita.",
   hist:"Courtois lo descubrió en 1811 quemando algas. Sus vapores violeta le dieron nombre."},
  {id:"Ba", sym:"Ba", name:"Bario", num:56, atk:3, def:4, type:'nonmetal', img:'img/Ba.png',
   eff:"⚔️🛡 Ataque/Defensa: combínala en el orden de la fórmula para formar una molécula y batirte.", info:"Verde en la pirotecnia.",
   hist:"Davy lo aisló en 1808. Su sulfato hace visibles tus radiografías digestivas."},
  {id:"W", sym:"W", name:"Wolframio", num:74, atk:4, def:4, type:'nonmetal', img:'img/W.png',
   eff:"⚔️🛡 Ataque/Defensa: combínala en el orden de la fórmula para formar una molécula y batirte.", info:"El punto de fusión más alto.",
   hist:"Los hermanos Elhuyar lo aislaron en 1783 en el País Vasco: el único elemento descubierto en España."},
  {id:"Bi", sym:"Bi", name:"Bismuto", num:83, atk:3, def:4, type:'nonmetal', img:'img/Bi.png',
   eff:"⚔️🛡 Ataque/Defensa: combínala en el orden de la fórmula para formar una molécula y batirte.", info:"Cristales de arcoíris.",
   hist:"Confundido con plomo durante siglos; Geoffroy demostró en 1753 que era otro metal."},
  {id:"Cs", sym:"Cs", name:"Cesio", num:55, atk:3, def:5, type:'nonmetal', img:'img/Cs.png',
   eff:"⚔️🛡 Ataque/Defensa: combínala en el orden de la fórmula para formar una molécula y batirte.", info:"Late en los relojes atómicos.",
   hist:"Bunsen y Kirchhoff lo descubrieron en 1860 por sus líneas azul cielo: el primer elemento hallado por espectroscopia."},
  {id:"U", sym:"U", name:"Uranio", num:92, atk:6, def:2, type:'nonmetal', img:'img/U.png',
   eff:"⚔️🛡 Ataque/Defensa: combínala en el orden de la fórmula para formar una molécula y batirte.", info:"Metal radiactivo. Fisión nuclear.",
   hist:"Klaproth lo aisló en 1789 y lo nombró por Urano. Con él Becquerel descubrió la radiactividad en 1896."},
  {id:"Ra", sym:"Ra", name:"Radio", num:88, atk:6, def:3, type:'nonmetal', img:'img/Ra.png',
   eff:"⚔️🛡 Ataque/Defensa: combínala en el orden de la fórmula para formar una molécula y batirte.", info:"Brilla solo en la oscuridad.",
   hist:"Marie y Pierre Curie lo aislaron en 1898 de toneladas de pechblenda. Les valió un Nobel… y les costó la salud."},
  {id:"Po", sym:"Po", name:"Polonio", num:84, atk:6, def:3, type:'nonmetal', img:'img/Po.png',
   eff:"⚔️🛡 Ataque/Defensa: combínala en el orden de la fórmula para formar una molécula y batirte.", info:"El veneno radiactivo más célebre.",
   hist:"Primer elemento de los Curie (1898), nombrado por la Polonia natal de Marie."},
];

/* ── Hechizos (7) — efectos reales implementados en game.js ── */
const SPELLS = [
  {id:"Pb", sym:"Pb", name:"Plomo", num:82, atk:0, def:0, type:'spell', img:'img/Pb.png',
   eff:"🛡 BLINDAJE: los elementos radiactivos rivales (U·Ra·Po) pierden el 50% de ATK y DEF esta batalla.", info:"El plomo detiene la radiación.",
   hist:"Los romanos lo usaban en tuberías: de plumbum viene «plomería». Tan denso que bloquea los rayos X."},
  {id:"He", sym:"He", name:"Helio", num:2, atk:0, def:0, type:'spell', img:'img/He.png',
   eff:"🎈 LIGEREZA: +2 DEF a tu jugada esta batalla. Flota y esquiva.", info:"Más ligero que el aire.",
   hist:"El único elemento descubierto fuera de la Tierra: visto en el espectro del Sol en 1868."},
  {id:"Ne", sym:"Ne", name:"Neón", num:10, atk:0, def:0, type:'spell', img:'img/Ne.png',
   eff:"💡 DESLUMBRAR: −2 ATK a la jugada rival esta batalla.", info:"Su brillo eléctrico ciega.",
   hist:"Ramsay y Travers lo hallaron en 1898; su hijo propuso el nombre: «nuevo». Encendió Las Vegas."},
  {id:"Ar", sym:"Ar", name:"Argón", num:18, atk:0, def:0, type:'spell', img:'img/Ar.png',
   eff:"🔕 ATMÓSFERA INERTE: anula los hechizos rivales esta batalla.", info:"Gas protector, como en la soldadura.",
   hist:"Rayleigh y Ramsay lo aislaron en 1894: «el perezoso», porque no reacciona con nada."},
  {id:"Au", sym:"Au", name:"Oro", num:79, atk:0, def:0, type:'spell', img:'img/Au.png',
   eff:"💰 FINANCIACIÓN: robas 3 cartas al instante.", info:"El oro paga los mejores laboratorios.",
   hist:"Obsesión de alquimistas y conquistadores. Tan inerte que sobrevive milenios intacto."},
  {id:"Pt", sym:"Pt", name:"Platino", num:78, atk:0, def:0, type:'spell', img:'img/Pt.png',
   eff:"⚗️ CATÁLISIS: +1 ATK y +1 DEF a tu jugada esta batalla.", info:"El platino acelera cualquier reacción.",
   hist:"Los españoles lo llamaron «platina» (plata pequeña) en el siglo XVIII y lo tiraban al río. Hoy cataliza tu tubo de escape."},
  {id:"Hg", sym:"Hg", name:"Mercurio", num:80, atk:0, def:0, type:'spell', img:'img/Hg.png',
   eff:"☠️ VAPOR TÓXICO: −2 DEF a la jugada rival esta batalla.", info:"Sus vapores envenenan la defensa.",
   hist:"El «agua viva» de los alquimistas. Volvió locos a los sombrereros del XIX — de ahí la expresión."},
];

/* ── Colores neón por carta ── */
const CARD_COLORS = {
  "H": "#7dd3fc",
  "Li": "#c084fc",
  "Be": "#a78bfa",
  "B": "#5eead4",
  "C": "#e2e8f0",
  "N": "#60a5fa",
  "O": "#fb7185",
  "F": "#34d399",
  "Na": "#c084fc",
  "Mg": "#a78bfa",
  "Al": "#9ca3af",
  "Si": "#5eead4",
  "P": "#fb923c",
  "S": "#facc15",
  "Cl": "#34d399",
  "K": "#c084fc",
  "Ca": "#a78bfa",
  "Ti": "#94a3b8",
  "V": "#94a3b8",
  "Cr": "#86efac",
  "Mn": "#94a3b8",
  "Fe": "#f87171",
  "Co": "#818cf8",
  "Ni": "#94a3b8",
  "Cu": "#fb923c",
  "Zn": "#94a3b8",
  "As": "#5eead4",
  "Se": "#fbbf24",
  "Br": "#f59e0b",
  "Sr": "#a78bfa",
  "Mo": "#94a3b8",
  "Ag": "#e5e7eb",
  "Cd": "#94a3b8",
  "Sn": "#9ca3af",
  "Sb": "#5eead4",
  "I": "#c084fc",
  "Ba": "#a78bfa",
  "W": "#94a3b8",
  "Bi": "#9ca3af",
  "Cs": "#c084fc",
  "U": "#a3e635",
  "Ra": "#a3e635",
  "Po": "#a3e635",
  "Pb": "#94a3b8",
  "He": "#fbbf24",
  "Ne": "#f472b6",
  "Ar": "#22d3ee",
  "Au": "#fde047",
  "Pt": "#e5e7eb",
  "Hg": "#f87171",
};

/* ── 290 moléculas válidas ── */
const VALID_MOLECULES = [
  {ids:["C"], name:"Carbono nativo", formula:"C", atk:2, def:2},
  {ids:["S"], name:"Azufre nativo", formula:"S", atk:3, def:1},
  {ids:["Cu"], name:"Cobre nativo", formula:"Cu", atk:2, def:3},
  {ids:["Ag"], name:"Plata nativa", formula:"Ag", atk:2, def:3},
  {ids:["Fe"], name:"Hierro meteórico", formula:"Fe", atk:2, def:3},
  {ids:["Bi"], name:"Bismuto nativo", formula:"Bi", atk:3, def:4},
  {ids:["U"], name:"Uranio", formula:"U", atk:6, def:2},
  {ids:["Ra"], name:"Radio", formula:"Ra", atk:6, def:3},
  {ids:["Po"], name:"Polonio", formula:"Po", atk:6, def:3},
  {ids:["H", "H"], name:"Dihidrógeno", formula:"H₂", atk:2, def:4},
  {ids:["N", "N"], name:"Dinitrógeno", formula:"N₂", atk:4, def:4},
  {ids:["O", "O"], name:"Dioxígeno", formula:"O₂", atk:4, def:2},
  {ids:["O", "O", "O"], name:"Ozono", formula:"O₃", atk:6, def:3},
  {ids:["F", "F"], name:"Diflúor", formula:"F₂", atk:4, def:2},
  {ids:["Cl", "Cl"], name:"Dicloro", formula:"Cl₂", atk:4, def:2},
  {ids:["Br", "Br"], name:"Dibromo", formula:"Br₂", atk:6, def:2},
  {ids:["I", "I"], name:"Diyodo", formula:"I₂", atk:6, def:2},
  {ids:["S", "S"], name:"Diazufre", formula:"S₂", atk:6, def:2},
  {ids:["H", "H", "O"], name:"Agua", formula:"H₂O", atk:4, def:5},
  {ids:["H", "H", "O", "O"], name:"Peróxido de hidrógeno", formula:"H₂O₂", atk:6, def:6},
  {ids:["H", "F"], name:"Fluoruro de hidrógeno", formula:"HF", atk:3, def:3},
  {ids:["H", "Cl"], name:"Cloruro de hidrógeno", formula:"HCl", atk:3, def:3},
  {ids:["H", "Br"], name:"Bromuro de hidrógeno", formula:"HBr", atk:4, def:3},
  {ids:["H", "I"], name:"Yoduro de hidrógeno", formula:"HI", atk:4, def:3},
  {ids:["H", "H", "S"], name:"Sulfuro de hidrógeno", formula:"H₂S", atk:5, def:5},
  {ids:["H", "H", "Se"], name:"Seleniuro de hidrógeno", formula:"H₂Se", atk:6, def:6},
  {ids:["N", "H", "H", "H"], name:"Amoníaco", formula:"NH₃", atk:5, def:8},
  {ids:["P", "H", "H", "H"], name:"Fosfina", formula:"PH₃", atk:6, def:9},
  {ids:["As", "H", "H", "H"], name:"Arsina", formula:"AsH₃", atk:6, def:9},
  {ids:["Sb", "H", "H", "H"], name:"Estibina", formula:"SbH₃", atk:6, def:10},
  {ids:["C", "H", "H", "H", "H"], name:"Metano", formula:"CH₄", atk:6, def:10},
  {ids:["Si", "H", "H", "H", "H"], name:"Silano", formula:"SiH₄", atk:7, def:11},
  {ids:["B", "H", "H", "H"], name:"Borano", formula:"BH₃", atk:6, def:8},
  {ids:["Li", "H"], name:"Hidruro de litio", formula:"LiH", atk:3, def:5},
  {ids:["Na", "H"], name:"Hidruro de sodio", formula:"NaH", atk:3, def:4},
  {ids:["K", "H"], name:"Hidruro de potasio", formula:"KH", atk:3, def:4},
  {ids:["Mg", "H", "H"], name:"Hidruro de magnesio", formula:"MgH₂", atk:4, def:7},
  {ids:["Ca", "H", "H"], name:"Hidruro de calcio", formula:"CaH₂", atk:4, def:7},
  {ids:["Sr", "H", "H"], name:"Hidruro de estroncio", formula:"SrH₂", atk:5, def:8},
  {ids:["Ba", "H", "H"], name:"Hidruro de bario", formula:"BaH₂", atk:5, def:8},
  {ids:["H", "C", "N"], name:"Cianuro de hidrógeno", formula:"HCN", atk:5, def:6},
  {ids:["H", "N", "N", "N"], name:"Azida de hidrógeno", formula:"HN₃", atk:7, def:8},
  {ids:["C", "O"], name:"Monóxido de carbono", formula:"CO", atk:4, def:3},
  {ids:["C", "O", "O"], name:"Dióxido de carbono", formula:"CO₂", atk:6, def:4},
  {ids:["N", "O"], name:"Óxido nítrico", formula:"NO", atk:4, def:3},
  {ids:["N", "O", "O"], name:"Dióxido de nitrógeno", formula:"NO₂", atk:6, def:4},
  {ids:["N", "N", "O"], name:"Gas de la risa", formula:"N₂O", atk:6, def:5},
  {ids:["N", "N", "O", "O", "O"], name:"Trióxido de dinitrógeno", formula:"N₂O₃", atk:10, def:7},
  {ids:["S", "O", "O"], name:"Dióxido de azufre", formula:"SO₂", atk:7, def:3},
  {ids:["S", "O", "O", "O"], name:"Trióxido de azufre", formula:"SO₃", atk:9, def:4},
  {ids:["Si", "O"], name:"Monóxido de silicio", formula:"SiO", atk:5, def:4},
  {ids:["Si", "O", "O"], name:"Sílice (cuarzo)", formula:"SiO₂", atk:7, def:5},
  {ids:["B", "B", "O", "O", "O"], name:"Trióxido de boro", formula:"B₂O₃", atk:12, def:7},
  {ids:["P", "O"], name:"Monóxido de fósforo", formula:"PO", atk:5, def:4},
  {ids:["Se", "O", "O"], name:"Dióxido de selenio", formula:"SeO₂", atk:8, def:4},
  {ids:["Se", "O", "O", "O"], name:"Trióxido de selenio", formula:"SeO₃", atk:10, def:5},
  {ids:["As", "As", "O", "O", "O"], name:"Arsénico blanco", formula:"As₂O₃", atk:12, def:9},
  {ids:["Sb", "Sb", "O", "O", "O"], name:"Trióxido de antimonio", formula:"Sb₂O₃", atk:12, def:11},
  {ids:["Cl", "Cl", "O"], name:"Monóxido de dicloro", formula:"Cl₂O", atk:6, def:3},
  {ids:["Cl", "O", "O"], name:"Dióxido de cloro", formula:"ClO₂", atk:6, def:3},
  {ids:["O", "F", "F"], name:"Difluoruro de oxígeno", formula:"OF₂", atk:6, def:3},
  {ids:["Li", "Li", "O"], name:"Óxido de litio", formula:"Li₂O", atk:6, def:7},
  {ids:["Na", "Na", "O"], name:"Óxido de sodio", formula:"Na₂O", atk:6, def:5},
  {ids:["Na", "Na", "O", "O"], name:"Peróxido de sodio", formula:"Na₂O₂", atk:8, def:6},
  {ids:["K", "K", "O"], name:"Óxido de potasio", formula:"K₂O", atk:6, def:5},
  {ids:["K", "O", "O"], name:"Superóxido de potasio", formula:"KO₂", atk:6, def:4},
  {ids:["Be", "O"], name:"Óxido de berilio", formula:"BeO", atk:5, def:7},
  {ids:["Mg", "O"], name:"Magnesia", formula:"MgO", atk:4, def:4},
  {ids:["Ca", "O"], name:"Cal viva", formula:"CaO", atk:4, def:4},
  {ids:["Ca", "O", "O"], name:"Peróxido de calcio", formula:"CaO₂", atk:6, def:5},
  {ids:["Sr", "O"], name:"Óxido de estroncio", formula:"SrO", atk:5, def:5},
  {ids:["Ba", "O"], name:"Óxido de bario", formula:"BaO", atk:5, def:5},
  {ids:["Ba", "O", "O"], name:"Peróxido de bario", formula:"BaO₂", atk:7, def:6},
  {ids:["Al", "Al", "O", "O", "O"], name:"Alúmina (corindón)", formula:"Al₂O₃", atk:12, def:9},
  {ids:["Ti", "O"], name:"Monóxido de titanio", formula:"TiO", atk:5, def:5},
  {ids:["Ti", "O", "O"], name:"Rutilo", formula:"TiO₂", atk:7, def:6},
  {ids:["V", "O"], name:"Monóxido de vanadio", formula:"VO", atk:5, def:5},
  {ids:["V", "O", "O"], name:"Dióxido de vanadio", formula:"VO₂", atk:7, def:6},
  {ids:["Cr", "O", "O", "O"], name:"Trióxido de cromo", formula:"CrO₃", atk:9, def:8},
  {ids:["Cr", "Cr", "O", "O", "O"], name:"Verde de cromo", formula:"Cr₂O₃", atk:12, def:13},
  {ids:["Mn", "O"], name:"Óxido de manganeso(II)", formula:"MnO", atk:4, def:5},
  {ids:["Mn", "O", "O"], name:"Pirolusita", formula:"MnO₂", atk:6, def:6},
  {ids:["Mn", "Mn", "O", "O", "O"], name:"Óxido de manganeso(III)", formula:"Mn₂O₃", atk:10, def:11},
  {ids:["Fe", "O"], name:"Wustita", formula:"FeO", atk:4, def:4},
  {ids:["Fe", "Fe", "O", "O", "O"], name:"Hematita", formula:"Fe₂O₃", atk:10, def:9},
  {ids:["Co", "O"], name:"Óxido de cobalto", formula:"CoO", atk:6, def:5},
  {ids:["Ni", "O"], name:"Óxido de níquel", formula:"NiO", atk:5, def:6},
  {ids:["Cu", "O"], name:"Tenorita", formula:"CuO", atk:4, def:4},
  {ids:["Cu", "Cu", "O"], name:"Cuprita", formula:"Cu₂O", atk:6, def:7},
  {ids:["Zn", "O"], name:"Cincita", formula:"ZnO", atk:4, def:5},
  {ids:["Mo", "O", "O"], name:"Dióxido de molibdeno", formula:"MoO₂", atk:8, def:7},
  {ids:["Mo", "O", "O", "O"], name:"Trióxido de molibdeno", formula:"MoO₃", atk:10, def:8},
  {ids:["W", "O", "O"], name:"Dióxido de wolframio", formula:"WO₂", atk:8, def:6},
  {ids:["W", "O", "O", "O"], name:"Trióxido de wolframio", formula:"WO₃", atk:10, def:7},
  {ids:["Cd", "O"], name:"Óxido de cadmio", formula:"CdO", atk:5, def:6},
  {ids:["Sn", "O"], name:"Óxido de estaño(II)", formula:"SnO", atk:5, def:5},
  {ids:["Sn", "O", "O"], name:"Casiterita", formula:"SnO₂", atk:7, def:6},
  {ids:["Bi", "Bi", "O", "O", "O"], name:"Óxido de bismuto", formula:"Bi₂O₃", atk:12, def:11},
  {ids:["Cs", "Cs", "O"], name:"Óxido de cesio", formula:"Cs₂O", atk:8, def:11},
  {ids:["U", "O", "O"], name:"Uraninita", formula:"UO₂", atk:10, def:4},
  {ids:["U", "O", "O", "O"], name:"Trióxido de uranio", formula:"UO₃", atk:12, def:5},
  {ids:["Ra", "O"], name:"Óxido de radio", formula:"RaO", atk:8, def:4},
  {ids:["Po", "O", "O"], name:"Dióxido de polonio", formula:"PoO₂", atk:10, def:5},
  {ids:["Na", "Cl"], name:"Sal común (halita)", formula:"NaCl", atk:4, def:3},
  {ids:["Na", "F"], name:"Fluoruro de sodio", formula:"NaF", atk:4, def:3},
  {ids:["Na", "Br"], name:"Bromuro de sodio", formula:"NaBr", atk:5, def:3},
  {ids:["Na", "I"], name:"Yoduro de sodio", formula:"NaI", atk:5, def:3},
  {ids:["K", "Cl"], name:"Silvina", formula:"KCl", atk:4, def:3},
  {ids:["K", "F"], name:"Fluoruro de potasio", formula:"KF", atk:4, def:3},
  {ids:["K", "Br"], name:"Bromuro de potasio", formula:"KBr", atk:5, def:3},
  {ids:["K", "I"], name:"Yoduro de potasio", formula:"KI", atk:5, def:3},
  {ids:["Li", "F"], name:"Fluoruro de litio", formula:"LiF", atk:4, def:4},
  {ids:["Li", "Cl"], name:"Cloruro de litio", formula:"LiCl", atk:4, def:4},
  {ids:["Li", "Br"], name:"Bromuro de litio", formula:"LiBr", atk:5, def:4},
  {ids:["Li", "I"], name:"Yoduro de litio", formula:"LiI", atk:5, def:4},
  {ids:["Cs", "Cl"], name:"Cloruro de cesio", formula:"CsCl", atk:5, def:6},
  {ids:["Cs", "F"], name:"Fluoruro de cesio", formula:"CsF", atk:5, def:6},
  {ids:["Be", "F", "F"], name:"Fluoruro de berilio", formula:"BeF₂", atk:7, def:8},
  {ids:["Be", "Cl", "Cl"], name:"Cloruro de berilio", formula:"BeCl₂", atk:7, def:8},
  {ids:["Mg", "F", "F"], name:"Sellaita", formula:"MgF₂", atk:6, def:5},
  {ids:["Mg", "Cl", "Cl"], name:"Cloruro de magnesio", formula:"MgCl₂", atk:6, def:5},
  {ids:["Mg", "Br", "Br"], name:"Bromuro de magnesio", formula:"MgBr₂", atk:8, def:5},
  {ids:["Ca", "F", "F"], name:"Fluorita", formula:"CaF₂", atk:6, def:5},
  {ids:["Ca", "Cl", "Cl"], name:"Cloruro de calcio", formula:"CaCl₂", atk:6, def:5},
  {ids:["Ca", "Br", "Br"], name:"Bromuro de calcio", formula:"CaBr₂", atk:8, def:5},
  {ids:["Ca", "I", "I"], name:"Yoduro de calcio", formula:"CaI₂", atk:8, def:5},
  {ids:["Sr", "F", "F"], name:"Fluoruro de estroncio", formula:"SrF₂", atk:7, def:6},
  {ids:["Sr", "Cl", "Cl"], name:"Cloruro de estroncio", formula:"SrCl₂", atk:7, def:6},
  {ids:["Ba", "F", "F"], name:"Fluoruro de bario", formula:"BaF₂", atk:7, def:6},
  {ids:["Ba", "Cl", "Cl"], name:"Cloruro de bario", formula:"BaCl₂", atk:7, def:6},
  {ids:["Al", "F", "F", "F"], name:"Fluoruro de aluminio", formula:"AlF₃", atk:9, def:6},
  {ids:["Al", "Cl", "Cl", "Cl"], name:"Cloruro de aluminio", formula:"AlCl₃", atk:9, def:6},
  {ids:["Al", "Br", "Br", "Br"], name:"Bromuro de aluminio", formula:"AlBr₃", atk:12, def:6},
  {ids:["Al", "I", "I", "I"], name:"Yoduro de aluminio", formula:"AlI₃", atk:12, def:6},
  {ids:["B", "F", "F", "F"], name:"Trifluoruro de boro", formula:"BF₃", atk:9, def:5},
  {ids:["B", "Cl", "Cl", "Cl"], name:"Tricloruro de boro", formula:"BCl₃", atk:9, def:5},
  {ids:["B", "Br", "Br", "Br"], name:"Tribromuro de boro", formula:"BBr₃", atk:12, def:5},
  {ids:["Si", "F", "F", "F", "F"], name:"Tetrafluoruro de silicio", formula:"SiF₄", atk:11, def:7},
  {ids:["Si", "Cl", "Cl", "Cl", "Cl"], name:"Tetracloruro de silicio", formula:"SiCl₄", atk:11, def:7},
  {ids:["Ti", "Cl", "Cl", "Cl"], name:"Tricloruro de titanio", formula:"TiCl₃", atk:9, def:7},
  {ids:["Ti", "Cl", "Cl", "Cl", "Cl"], name:"Tetracloruro de titanio", formula:"TiCl₄", atk:11, def:8},
  {ids:["V", "Cl", "Cl", "Cl"], name:"Tricloruro de vanadio", formula:"VCl₃", atk:9, def:7},
  {ids:["V", "Cl", "Cl", "Cl", "Cl"], name:"Tetracloruro de vanadio", formula:"VCl₄", atk:11, def:8},
  {ids:["Cr", "Cl", "Cl"], name:"Cloruro de cromo(II)", formula:"CrCl₂", atk:7, def:7},
  {ids:["Cr", "Cl", "Cl", "Cl"], name:"Cloruro de cromo(III)", formula:"CrCl₃", atk:9, def:8},
  {ids:["Mn", "Cl", "Cl"], name:"Cloruro de manganeso", formula:"MnCl₂", atk:6, def:6},
  {ids:["Mn", "F", "F"], name:"Fluoruro de manganeso", formula:"MnF₂", atk:6, def:6},
  {ids:["Fe", "Cl", "Cl"], name:"Cloruro de hierro(II)", formula:"FeCl₂", atk:6, def:5},
  {ids:["Fe", "Cl", "Cl", "Cl"], name:"Cloruro férrico", formula:"FeCl₃", atk:8, def:6},
  {ids:["Fe", "F", "F", "F"], name:"Fluoruro férrico", formula:"FeF₃", atk:8, def:6},
  {ids:["Fe", "Br", "Br"], name:"Bromuro de hierro(II)", formula:"FeBr₂", atk:8, def:5},
  {ids:["Co", "Cl", "Cl"], name:"Cloruro de cobalto", formula:"CoCl₂", atk:8, def:6},
  {ids:["Co", "F", "F"], name:"Fluoruro de cobalto", formula:"CoF₂", atk:8, def:6},
  {ids:["Ni", "Cl", "Cl"], name:"Cloruro de níquel", formula:"NiCl₂", atk:7, def:7},
  {ids:["Ni", "F", "F"], name:"Fluoruro de níquel", formula:"NiF₂", atk:7, def:7},
  {ids:["Cu", "Cl"], name:"Nantokita", formula:"CuCl", atk:4, def:4},
  {ids:["Cu", "Cl", "Cl"], name:"Cloruro cúprico", formula:"CuCl₂", atk:6, def:5},
  {ids:["Zn", "Cl", "Cl"], name:"Cloruro de cinc", formula:"ZnCl₂", atk:6, def:6},
  {ids:["Zn", "F", "F"], name:"Fluoruro de cinc", formula:"ZnF₂", atk:6, def:6},
  {ids:["Ag", "F"], name:"Fluoruro de plata", formula:"AgF", atk:4, def:4},
  {ids:["Ag", "Cl"], name:"Clorargirita", formula:"AgCl", atk:4, def:4},
  {ids:["Ag", "Br"], name:"Bromuro de plata", formula:"AgBr", atk:5, def:4},
  {ids:["Ag", "I"], name:"Yoduro de plata", formula:"AgI", atk:5, def:4},
  {ids:["Cd", "Cl", "Cl"], name:"Cloruro de cadmio", formula:"CdCl₂", atk:7, def:7},
  {ids:["Cd", "F", "F"], name:"Fluoruro de cadmio", formula:"CdF₂", atk:7, def:7},
  {ids:["Sn", "Cl", "Cl"], name:"Cloruro de estaño(II)", formula:"SnCl₂", atk:7, def:6},
  {ids:["Sn", "Cl", "Cl", "Cl", "Cl"], name:"Cloruro de estaño(IV)", formula:"SnCl₄", atk:11, def:8},
  {ids:["Sn", "F", "F"], name:"Fluoruro de estaño", formula:"SnF₂", atk:7, def:6},
  {ids:["Sb", "Cl", "Cl", "Cl"], name:"Tricloruro de antimonio", formula:"SbCl₃", atk:9, def:7},
  {ids:["Sb", "F", "F", "F"], name:"Trifluoruro de antimonio", formula:"SbF₃", atk:9, def:7},
  {ids:["As", "Cl", "Cl", "Cl"], name:"Tricloruro de arsénico", formula:"AsCl₃", atk:9, def:6},
  {ids:["As", "F", "F", "F"], name:"Trifluoruro de arsénico", formula:"AsF₃", atk:9, def:6},
  {ids:["Bi", "Cl", "Cl", "Cl"], name:"Cloruro de bismuto", formula:"BiCl₃", atk:9, def:7},
  {ids:["Bi", "F", "F", "F"], name:"Fluoruro de bismuto", formula:"BiF₃", atk:9, def:7},
  {ids:["U", "Cl", "Cl", "Cl", "Cl"], name:"Tetracloruro de uranio", formula:"UCl₄", atk:14, def:6},
  {ids:["U", "F", "F", "F", "F"], name:"Sal verde de uranio", formula:"UF₄", atk:14, def:6},
  {ids:["Ra", "Cl", "Cl"], name:"Cloruro de radio", formula:"RaCl₂", atk:10, def:5},
  {ids:["Po", "Cl", "Cl"], name:"Dicloruro de polonio", formula:"PoCl₂", atk:10, def:5},
  {ids:["Po", "Cl", "Cl", "Cl", "Cl"], name:"Tetracloruro de polonio", formula:"PoCl₄", atk:14, def:7},
  {ids:["Cl", "F"], name:"Monofluoruro de cloro", formula:"ClF", atk:4, def:2},
  {ids:["Cl", "F", "F", "F"], name:"Trifluoruro de cloro", formula:"ClF₃", atk:8, def:4},
  {ids:["Br", "F"], name:"Monofluoruro de bromo", formula:"BrF", atk:5, def:2},
  {ids:["Br", "F", "F", "F"], name:"Trifluoruro de bromo", formula:"BrF₃", atk:9, def:4},
  {ids:["Br", "Cl"], name:"Cloruro de bromo", formula:"BrCl", atk:5, def:2},
  {ids:["I", "Cl"], name:"Monocloruro de yodo", formula:"ICl", atk:5, def:2},
  {ids:["I", "Br"], name:"Monobromuro de yodo", formula:"IBr", atk:6, def:2},
  {ids:["C", "S", "S"], name:"Disulfuro de carbono", formula:"CS₂", atk:8, def:4},
  {ids:["C", "O", "S"], name:"Sulfuro de carbonilo", formula:"COS", atk:7, def:4},
  {ids:["S", "Cl", "Cl"], name:"Dicloruro de azufre", formula:"SCl₂", atk:7, def:3},
  {ids:["S", "S", "Cl", "Cl"], name:"Monocloruro de azufre", formula:"S₂Cl₂", atk:10, def:4},
  {ids:["S", "O", "Cl", "Cl"], name:"Cloruro de tionilo", formula:"SOCl₂", atk:9, def:4},
  {ids:["S", "O", "O", "Cl", "Cl"], name:"Cloruro de sulfurilo", formula:"SO₂Cl₂", atk:11, def:5},
  {ids:["S", "F", "F", "F", "F"], name:"Tetrafluoruro de azufre", formula:"SF₄", atk:11, def:5},
  {ids:["Na", "Na", "S"], name:"Sulfuro de sodio", formula:"Na₂S", atk:7, def:5},
  {ids:["K", "K", "S"], name:"Sulfuro de potasio", formula:"K₂S", atk:7, def:5},
  {ids:["Li", "Li", "S"], name:"Sulfuro de litio", formula:"Li₂S", atk:7, def:7},
  {ids:["Mg", "S"], name:"Sulfuro de magnesio", formula:"MgS", atk:5, def:4},
  {ids:["Ca", "S"], name:"Oldhamita", formula:"CaS", atk:5, def:4},
  {ids:["Sr", "S"], name:"Sulfuro de estroncio", formula:"SrS", atk:6, def:5},
  {ids:["Ba", "S"], name:"Sulfuro de bario", formula:"BaS", atk:6, def:5},
  {ids:["Fe", "S"], name:"Troilita", formula:"FeS", atk:5, def:4},
  {ids:["Fe", "S", "S"], name:"Pirita (oro de los tontos)", formula:"FeS₂", atk:8, def:5},
  {ids:["Co", "S"], name:"Sulfuro de cobalto", formula:"CoS", atk:7, def:5},
  {ids:["Ni", "S"], name:"Millerita", formula:"NiS", atk:6, def:6},
  {ids:["Cu", "S"], name:"Covelina", formula:"CuS", atk:5, def:4},
  {ids:["Cu", "Cu", "S"], name:"Calcosina", formula:"Cu₂S", atk:7, def:7},
  {ids:["Zn", "S"], name:"Esfalerita", formula:"ZnS", atk:5, def:5},
  {ids:["Ag", "Ag", "S"], name:"Argentita", formula:"Ag₂S", atk:7, def:7},
  {ids:["Cd", "S"], name:"Greenockita", formula:"CdS", atk:6, def:6},
  {ids:["Sn", "S"], name:"Herzenbergita", formula:"SnS", atk:6, def:5},
  {ids:["Sn", "S", "S"], name:"Oro musivo", formula:"SnS₂", atk:9, def:6},
  {ids:["Sb", "Sb", "S", "S", "S"], name:"Antimonita", formula:"Sb₂S₃", atk:15, def:11},
  {ids:["As", "As", "S", "S", "S"], name:"Oropimente", formula:"As₂S₃", atk:15, def:9},
  {ids:["Mo", "S", "S"], name:"Molibdenita", formula:"MoS₂", atk:10, def:7},
  {ids:["W", "S", "S"], name:"Tungstenita", formula:"WS₂", atk:10, def:6},
  {ids:["Mn", "S"], name:"Alabandita", formula:"MnS", atk:5, def:5},
  {ids:["Si", "S", "S"], name:"Disulfuro de silicio", formula:"SiS₂", atk:9, def:5},
  {ids:["B", "B", "S", "S", "S"], name:"Sulfuro de boro", formula:"B₂S₃", atk:15, def:7},
  {ids:["Bi", "Bi", "S", "S", "S"], name:"Bismutina", formula:"Bi₂S₃", atk:15, def:11},
  {ids:["Zn", "Se"], name:"Seleniuro de cinc", formula:"ZnSe", atk:6, def:6},
  {ids:["Cd", "Se"], name:"Seleniuro de cadmio", formula:"CdSe", atk:7, def:7},
  {ids:["Fe", "Se"], name:"Seleniuro de hierro", formula:"FeSe", atk:6, def:5},
  {ids:["Na", "Na", "Se"], name:"Seleniuro de sodio", formula:"Na₂Se", atk:8, def:6},
  {ids:["Ag", "Ag", "Se"], name:"Naumannita", formula:"Ag₂Se", atk:8, def:8},
  {ids:["B", "N"], name:"Nitruro de boro", formula:"BN", atk:5, def:4},
  {ids:["Al", "N"], name:"Nitruro de aluminio", formula:"AlN", atk:5, def:5},
  {ids:["Ti", "N"], name:"Nitruro de titanio", formula:"TiN", atk:5, def:6},
  {ids:["V", "N"], name:"Nitruro de vanadio", formula:"VN", atk:5, def:6},
  {ids:["Mg", "Mg", "Mg", "N", "N"], name:"Nitruro de magnesio", formula:"Mg₃N₂", atk:10, def:13},
  {ids:["Ca", "Ca", "Ca", "N", "N"], name:"Nitruro de calcio", formula:"Ca₃N₂", atk:10, def:13},
  {ids:["Li", "Li", "Li", "N"], name:"Nitruro de litio", formula:"Li₃N", atk:8, def:11},
  {ids:["Na", "C", "N"], name:"Cianuro de sodio", formula:"NaCN", atk:6, def:6},
  {ids:["K", "C", "N"], name:"Cianuro de potasio", formula:"KCN", atk:6, def:6},
  {ids:["Ca", "C", "C"], name:"Carburo de calcio", formula:"CaC₂", atk:6, def:7},
  {ids:["Si", "C"], name:"Carborundo", formula:"SiC", atk:5, def:5},
  {ids:["Ti", "C"], name:"Carburo de titanio", formula:"TiC", atk:5, def:6},
  {ids:["W", "C"], name:"Widia", formula:"WC", atk:6, def:6},
  {ids:["B", "B", "B", "B", "C"], name:"Carburo de boro", formula:"B₄C", atk:14, def:10},
  {ids:["Fe", "Fe", "Fe", "C"], name:"Cementita", formula:"Fe₃C", atk:8, def:11},
  {ids:["V", "C"], name:"Carburo de vanadio", formula:"VC", atk:5, def:6},
  {ids:["Mg", "Mg", "Si"], name:"Siliciuro de magnesio", formula:"Mg₂Si", atk:7, def:9},
  {ids:["Ca", "C", "N", "N"], name:"Cianamida cálcica", formula:"CaCN₂", atk:8, def:9},
  {ids:["C", "C", "N", "N"], name:"Cianógeno", formula:"C₂N₂", atk:8, def:8},
  {ids:["Na", "O", "H"], name:"Sosa cáustica", formula:"NaOH", atk:5, def:5},
  {ids:["K", "O", "H"], name:"Potasa cáustica", formula:"KOH", atk:5, def:5},
  {ids:["Li", "O", "H"], name:"Hidróxido de litio", formula:"LiOH", atk:5, def:6},
  {ids:["Cs", "O", "H"], name:"Hidróxido de cesio", formula:"CsOH", atk:6, def:8},
  {ids:["Mg", "O", "H", "O", "H"], name:"Leche de magnesia", formula:"Mg(OH)₂", atk:8, def:9},
  {ids:["Ca", "O", "H", "O", "H"], name:"Cal apagada", formula:"Ca(OH)₂", atk:8, def:9},
  {ids:["Cu", "O", "H", "O", "H"], name:"Hidróxido de cobre", formula:"Cu(OH)₂", atk:8, def:9},
  {ids:["Zn", "O", "H", "O", "H"], name:"Hidróxido de cinc", formula:"Zn(OH)₂", atk:8, def:10},
  {ids:["Na", "N", "O", "O"], name:"Nitrito de sodio", formula:"NaNO₂", atk:8, def:6},
  {ids:["K", "N", "O", "O"], name:"Nitrito de potasio", formula:"KNO₂", atk:8, def:6},
  {ids:["Na", "N", "O", "O", "O"], name:"Nitrato de Chile", formula:"NaNO₃", atk:10, def:7},
  {ids:["K", "N", "O", "O", "O"], name:"Salitre", formula:"KNO₃", atk:10, def:7},
  {ids:["Ag", "N", "O", "O", "O"], name:"Piedra infernal", formula:"AgNO₃", atk:10, def:8},
  {ids:["Na", "Cl", "O"], name:"Lejía (hipoclorito)", formula:"NaClO", atk:6, def:4},
  {ids:["Na", "Cl", "O", "O"], name:"Clorito de sodio", formula:"NaClO₂", atk:8, def:5},
  {ids:["K", "Cl", "O", "O", "O"], name:"Clorato de potasio", formula:"KClO₃", atk:10, def:6},
  {ids:["Ca", "C", "O", "O", "O"], name:"Calcita (mármol)", formula:"CaCO₃", atk:10, def:8},
  {ids:["Mg", "C", "O", "O", "O"], name:"Magnesita", formula:"MgCO₃", atk:10, def:8},
  {ids:["Ba", "C", "O", "O", "O"], name:"Witherita", formula:"BaCO₃", atk:11, def:9},
  {ids:["Sr", "C", "O", "O", "O"], name:"Estroncianita", formula:"SrCO₃", atk:11, def:9},
  {ids:["Fe", "C", "O", "O", "O"], name:"Siderita", formula:"FeCO₃", atk:10, def:8},
  {ids:["Zn", "C", "O", "O", "O"], name:"Smithsonita", formula:"ZnCO₃", atk:10, def:9},
  {ids:["Mn", "C", "O", "O", "O"], name:"Rodocrosita", formula:"MnCO₃", atk:10, def:9},
  {ids:["H", "N", "O", "O", "O"], name:"Ácido nítrico", formula:"HNO₃", atk:9, def:7},
  {ids:["H", "N", "O", "O"], name:"Ácido nitroso", formula:"HNO₂", atk:7, def:6},
  {ids:["H", "Cl", "O"], name:"Ácido hipocloroso", formula:"HClO", atk:5, def:4},
  {ids:["H", "Cl", "O", "O"], name:"Ácido cloroso", formula:"HClO₂", atk:7, def:5},
  {ids:["H", "Br", "O"], name:"Ácido hipobromoso", formula:"HBrO", atk:6, def:4},
  {ids:["H", "I", "O"], name:"Ácido hipoyodoso", formula:"HIO", atk:6, def:4},
  {ids:["H", "C", "O", "O", "H"], name:"Ácido fórmico", formula:"CH₂O₂", atk:8, def:8},
  {ids:["C", "H", "H", "O"], name:"Formaldehído", formula:"CH₂O", atk:6, def:7},
  {ids:["C", "C", "H", "H"], name:"Acetileno", formula:"C₂H₂", atk:6, def:8},
  {ids:["C", "Cl", "Cl", "Cl", "Cl"], name:"Tetracloruro de carbono", formula:"CCl₄", atk:10, def:6},
  {ids:["C", "H", "Cl", "Cl", "Cl"], name:"Cloroformo", formula:"CHCl₃", atk:9, def:7},
  {ids:["C", "F", "F", "F", "F"], name:"Tetrafluorometano", formula:"CF₄", atk:10, def:6},
  {ids:["C", "H", "H", "Cl", "Cl"], name:"Diclorometano", formula:"CH₂Cl₂", atk:8, def:8},
  {ids:["C", "Br", "Br", "Br", "Br"], name:"Tetrabromuro de carbono", formula:"CBr₄", atk:14, def:6},
  {ids:["C", "O", "Cl", "Cl"], name:"Fosgeno", formula:"COCl₂", atk:8, def:5},
  {ids:["N", "F", "F", "F"], name:"Trifluoruro de nitrógeno", formula:"NF₃", atk:8, def:5},
  {ids:["N", "Cl", "Cl", "Cl"], name:"Tricloruro de nitrógeno", formula:"NCl₃", atk:8, def:5},
  {ids:["P", "F", "F", "F"], name:"Trifluoruro de fósforo", formula:"PF₃", atk:9, def:6},
  {ids:["P", "Cl", "Cl", "Cl"], name:"Tricloruro de fósforo", formula:"PCl₃", atk:9, def:6},
  {ids:["P", "Br", "Br", "Br"], name:"Tribromuro de fósforo", formula:"PBr₃", atk:12, def:6},
  {ids:["P", "I", "I", "I"], name:"Triyoduro de fósforo", formula:"PI₃", atk:12, def:6},
  {ids:["P", "O", "Cl", "Cl", "Cl"], name:"Oxicloruro de fósforo", formula:"POCl₃", atk:11, def:7},
  {ids:["N", "O", "Cl"], name:"Cloruro de nitrosilo", formula:"NOCl", atk:6, def:4},
  {ids:["N", "O", "Br"], name:"Bromuro de nitrosilo", formula:"NOBr", atk:7, def:4},
];
